version: '2'

services:
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn:1.19
    restart: always
    ports:
      - 9091:9091
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOCAL_NETWORK=192.168.1.0/24
      - TRANSMISSION_DOWNLOAD_DIR=/data/complete
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_SPEED_LIMIT_DOWN=5000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=1500
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - PUID=1000
      - PGID=1000
    env_file:
      - .env
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
